version: '3.4'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sql19-latest
    ports:
      - "1433:1433"
    restart: always
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: 12qw!@QW
      MSSQL_PID: Express
      MSSQL_LCID: 1049
      MSSQL_COLLATION: Cyrillic_General_CI_AS
      user: ${CURRENT_UID}
#    volumes:
#      - /var/opt/mssql:/var/opt/mssql
#      - /backup:/backup
