version: '3.4'

services:
  nscreg.server:
    image: ${DOCKER_REGISTRY-}nscregserver
    build:
      context: .
      dockerfile: src/nscreg.Server/Dockerfile
    volumes:
        - /docker/src/nscreg.Server/uploads:/app/uploads

  elasticsearch:
   container_name: elasticsearch
   image: docker.elastic.co/elasticsearch/elasticsearch:8.1.0
   ports:
    - 9200:9200
   volumes:
    - elasticsearch-data:/usr/share/elasticsearch/data
   environment:
    - xpack.monitoring.enabled=true
    - xpack.watcher.enabled=false
    - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    - discovery.type=single-node
   networks:
    - elastic
  
networks:
  elastic:
    driver: bridge

volumes:
  elasticsearch-data:
