name: Node.js and .NET CI

on:
  push:
    branches: [ "CreateNewClassWithNewWithoutDI" ]
  pull_request:
    branches: [ "CreateNewClassWithNewWithoutDI" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        dotnet-version: [3.1.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Use .NET ${{ matrix.dotnet-version }}
      uses: actions/setup-dotnet@v3.0.0
      with:
        dotnet-version: ${{ matrix.dotnet-version }}

    - run: npm ci
    - run: npm run build --if-present
    - run: npm test

    - run: dotnet restore nscreg.sln
    - run: dotnet build --no-restore nscreg.sln
#    - run: dotnet test --no-build --verbosity normal
